on: [push, pull_request]

name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      
      - name: Set up Zola Environment
        env:
          ZOLA_VERSION: 0.17.2 # 指定你的 Zola 版本
        run: |
          curl -sSL -o zola.tar.gz https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola.tar.gz
          chmod +x zola
          mv zola /usr/local/bin/
          zola --version
      
      - name: Build Zola Blog
        run: zola build
      
      - name: Create Environment File
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: echo "TOKEN=$TOKEN" >> $GITHUB_ENV
      
      - name: Deploy to GitHub Pages
        uses: shalzz/zola-deploy-action@v0.17.2
